/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Sapcy",
  "tagline": "",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "markdown": {
    "mermaid": true,
    "format": "detect",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid",
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true,
        "docsRouteBasePath": "/blog",
        "indexBlog": false,
        "searchBarShortcutHint": true,
        "searchBarPosition": "left"
      }
    ]
  ],
  "url": "https://sapcy.github.io",
  "baseUrl": "/",
  "organizationName": "sapcy",
  "projectName": "playbook",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "ko",
    "locales": [
      "ko"
    ],
    "localeConfigs": {
      "ko": {
        "label": "한국어",
        "htmlLang": "ko",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "blog",
          "sidebarPath": "./sidebars.ts",
          "tags": "tags.yml",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-client-redirects",
      {}
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ],
    "./plugins/transpile-sapcy-packages.js"
  ],
  "themeConfig": {
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {
        "themeVariables": {
          "darkMode": true,
          "primaryColor": "#2C3038",
          "primaryTextColor": "#ECEEF4",
          "primaryBorderColor": "#9AA0AD",
          "lineColor": "#9AA0AD",
          "secondaryColor": "#22262D",
          "tertiaryColor": "#1B1F25",
          "noteBkgColor": "#22262D",
          "noteTextColor": "#B4BAC8",
          "fontFamily": "Inter, sans-serif"
        }
      }
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Devlog",
      "logo": {
        "alt": "Playbook 로고",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/blog",
          "position": "left",
          "label": "블로그"
        },
        {
          "to": "/project",
          "label": "프로젝트",
          "position": "left"
        },
        {
          "to": "/blog/tags",
          "label": "태그",
          "position": "left"
        },
        {
          "to": "/info",
          "label": "​",
          "position": "right",
          "className": "header-info-link",
          "aria-label": "정보"
        },
        {
          "href": "https://github.com/sapcy/sapcy.github.io",
          "className": "header-github-link",
          "aria-label": "GitHub repository",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "블로그",
          "items": [
            {
              "label": "문서 허브",
              "to": "/blog"
            },
            {
              "label": "태그",
              "to": "/blog/tags"
            }
          ]
        },
        {
          "title": "커뮤니티",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/sapcy/sapcy.github.io"
            }
          ]
        },
        {
          "title": "더보기",
          "items": [
            {
              "label": "정보",
              "to": "/info"
            },
            {
              "label": "프로젝트",
              "to": "/project"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Playbook. Docusaurus로 제작되었습니다."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "defaultLanguage": "text",
      "additionalLanguages": [
        "java",
        "kotlin",
        "groovy",
        "properties",
        "yaml",
        "bash",
        "http",
        "diff",
        "sql",
        "cpp"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
